import java.util.ArrayList;
import java.util.Iterator;
public interface Subject {
   void registerObserver(Observer o);
   void removeObserver(Observer o);
   void notifyObservers();
   int size();
   void addComponent(Component component);
   void removeComponent(Component component);
   Component getChild(int child);
   int getCollisionTime();
   int getSocialDistance();
   int getSpeed();
   boolean isMask();
   void move();
   boolean isInfected();
   double probInfected();
   void print();
   Iterator createIterator();
   int getXCoordinate();
   int getYCoordinate();
   ArrayList getAllXCoordinate();
   ArrayList getAllYCoordinate();
   double getRFactor();
   boolean getInterSection();
   void setInterSection(boolean interSectionFlag);
   double getProbInfectedFactor();
   void setProbInfectedFactor(double prob);
   ArrayList getInfectedOrHealtyBoolean();
   void setIsInfected(boolean flag);
   ArrayList getPeopleInHospital();
   int numberOfInfected();
   void setInHospital(boolean flag);
   boolean getInHospital();
   long getInfectedStartTime();
   void setInfectedStartTime(long infectedStartTime);
   long getHospitalTime();
   void setHospitalTime();
   boolean isDead();
   void setDead(boolean dead);
   ArrayList getIsDead();
   double getZ();
   boolean isIntersection();
   void setIntersection(boolean intersection) ;
   boolean getIntersection();
   long getInterSectionTime() ;
   void setInterSectionTime(long interSectionTime) ;
   int getRecoveringPatient();
   void setRecoveringPatient(int recoveringPatient);
   void setZFactor(double factor);
   void setRFactor(double factor);
   void setCoordinateAfterInterSection(int x,int y);
}